name: Print runner machine data

on:
   workflow_dispatch:

jobs:
  ls-in-current-dir:
    runs-on: self-hosted
    name: list files
    steps:
      - uses: actions/checkout@v3
      - name: list using ls command
        run: |
             echo "Printing current dir content:"
             ls -la /home/gaurav/
      - name: print Default github env variables
        run: |
             echo "printing GITHUB_WORKSPACE:"
             echo "${GITHUB_WORKSPACE}"
             
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.MOCK_REPO_KEY}}
             
      - name: print SSH_AUTH_SOCK env variables
        run: |
             echo "printing SSH_AUTH_SOCK variable:"
             echo "${{env.SSH_AUTH_SOCK}}"
             
  check-persist-ssh-agent:
      runs-on: self-hosted
      needs: [ls-in-current-dir]
      name: check ssh-agent in diff job
      steps:
         - uses: actions/checkout@v3
         - name: print ssh agent socket if exists
           run: |
                echo "printing SSH_AUTH_SOCK variable in diff job:"
                echo "${{env.SSH_AUTH_SOCK}}"
