name: Print runner machine data

on:
   workflow_dispatch:

jobs:
  ls-in-current-dir:
    runs-on: self-hosted
    name: list files
    steps:
      - uses: actions/checkout@v3
      - name: list using ls command
        run: |
             echo "Printing current dir content:"
             ls -la /home/gaurav/
