name: Print local machine data

on:
   workflow_dispatch:

jobs:
  ls-in-current-dir:
    runs-on: self-hosted
    name: list files
    steps:
      - name: list using ls command
        run: |
             echo "Printing current dir content:"
             ls
